name: Build test NVIDIA driver patches

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

jobs:
  build-validation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kernel: [legacy, stable, mainline]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build against the ${{ matrix.kernel }} kernel
        run: make test-${{ matrix.kernel }}

      - name: Build against the ${{ matrix.kernel }} kernel with staging patches
        run: make test-${{ matrix.kernel }}-staging
